// <auto-generated />
using System;
using LigaTyperow.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LigaTyperow.Migrations
{
    [DbContext(typeof(LTContext))]
    [Migration("20191022174857_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("LigaTyperow.Models.Footballer", b =>
                {
                    b.Property<int>("FootballerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FootballerId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("Footballers");
                });

            modelBuilder.Entity("LigaTyperow.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamATeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamBTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("TeamATeamId");

                    b.HasIndex("TeamBTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LigaTyperow.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LigaTyperow.Models.Footballer", b =>
                {
                    b.HasOne("LigaTyperow.Models.Match", null)
                        .WithMany("Scorers")
                        .HasForeignKey("MatchId");

                    b.HasOne("LigaTyperow.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LigaTyperow.Models.Match", b =>
                {
                    b.HasOne("LigaTyperow.Models.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamATeamId");

                    b.HasOne("LigaTyperow.Models.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
